### ISSUE TITLE
NWheels.Micro 

### ISSUE THREAD

**Issue by felix-b** [nwheels-io/NWheels#31]
The idea is to create a set of small utility-like facades over different functional subsystems of NWheels.

Requirements:

- make it unobtrusive; require no more than 1 reference per utility; require no NWheels attributes or ancestors (but do allow using them).
- inverse the control: let arbitrary application code call the utilities, rather than host and dispatch calls to application components.
- make it consumable as NuGet packages, 1 package per utility; and maybe 1 additional package, for all utilities together.
- require no special setup in the application code (e.g. microservice.xml or feature loaders).
- allow one-shot calls to perform tasks, e.g. ```NWheels.Micro.Deserialize<MyObject>(bytes)``` or 
```NWheels.Micro.CreateTcpServer(myService)```.
- consume assemblies and reuse code of the full NWheels version

Such approach would lower entry level of knowledge and commitment for our potential users. They will be able to start small and grow as needed.

In comparison to utility facades, using the full version of NWheels should still be beneficial. Features like high availability clusters, in-memory actor grid, automated deployment, and many more, will be only available in the full version. The full version will also provide better startup times, better runtime performance, and better visibility of generated code.

**Comment by felix-b** [comment]
Any thoughts are welcome....

**Comment by ILyaIL83** [comment]
Good idea for minimizing entry level but adds complexity to knowledge base and configurability, but if it uses/creates under the hood the same mechanism of FeatureLoaders and microservice.xml... So how user code will be run?

**Comment by felix-b** [comment]
The idea is create DI container and invoke feature loaders in static constructors, but without MicroserviceHost.

**Comment by felix-b** [comment]
Utility facades are an alternative to MicroserviceHost. Lifecycle listeners that will be instantiated by one-shot calls to facafes, will get all notifications (Configure through Activate) at once.

**Comment by ILyaIL83** [comment]
It's still not clear what code should be written by user except registration itself. "Alternative to" means separate/parallel mechanism, then it sounds like marketing or Asp.Net Form for desktop developers. Maintain and understand two mechanism more difficult IMHO.

**Comment by felix-b** [comment]
@ILyaIL83, you're right - here we create an alternative entry point, which is a mechanism parallel to ```MicroserviceHost```. Beyond the entry point though, all the same functionality should be reused as is. Now, ```MicroserviceHost``` is ~800 lines of code, so that the proportion of separate/parallel mechanism  to understand and maintain will be getting less and less significant as NWheels grows. 

As for marketing, it basically _is_ marketing, because this is how we can get significantly more users, I'd expect by an order of magnitude. We want users because we want contributors, and the vast majority of contributors are users in the first place.

Nevertheless, from our perspective, ```MicroserviceHost``` is the mainstream and preferred way of using NWheels, and it fully exposes all available functionality, as opposed to utility facades. User who will be successful at using utility facades, will eventually fully adopt NWheels and start using ```MicroserviceHost``` instead.

I would not agree with a comparison to ASP.NET WebForms, as WebForms proved to be a fundametnally incorrect concept, and as such, all of its implementation went the wrong path. In contrast, here we are talking about creating just a different entry point to all the same functionality.

**Comment by felix-b** [comment]
### Proposed implementation

- Have a static member that refers to singleton instance of the DI container
- Lazily execute feature loaders. A static class named like ```LazyLoadedFeatures``` can take this responsibility. It will provide a method like ```void EnsureFeatureLoaded<TFeature>() where TFeature : class, IFeatureLoader```.
- On every one-shot call to a utility facade, the utility will first call ```EnsureFeatureLoaded``` for every feature it depends on.

#### Dynamically compiled components

Utility facades won't be able to take advantage of running precompiled. All dynamic components will be lazily compiled on the fly. With ```RoslynTypeFactoryBackend```, this means having a separate assembly for each graph of dynamic components. This may end up having tens of separate assemblies with runtime types. If we put those assemblies into a separate folder, that would not to be such an inconvenience.

An alternative solution is implement ```ReflectionEmitTypeFactoryBackend```, which only creates one assembly in memory. But that would be really maintenance of two big different mechanisms, which should be preferably avoided.

**Comment by ILyaIL83** [comment]
As we discussed Compilation, Configuration and Endpoint will be available at the beginning until we     see demand for more for marketing reasons.
