### ISSUE TITLE
GC-free asynchronous programming model? or Task?

### ISSUE THREAD

**Issue by felix-b** [nwheels-io/NWheels#52]
### UPDATE

Assumptions listed below proved to be wrong (see benchmark later in the thread). This issue is open because we need to understand - WHY.

### Problem

Current convention for asynchronous programming in .NET is writing ```async``` methods that return ```Task``` objects. This approach has inherent performance overhead, because under heavy load, it causes huge lot of ```Task``` objects to be allocated and collected by the GC.

Example: suppose we have 3 async functions F, G, and K, like these:
```c#
async Task<string> F()
{
    // ...do some processing
    return await G();
}
async Task<string> G()
{
    // ...do some processing
    return await K();
}
async Task<string> K()
{
    // ...do some processing
    return await .....;
}
```
Every call to F() results in 3 `Task` objects being allocated. If F() is invoked 1 million times per second, we end up allocation 3 millions of objects every second. This is really bad, especially for low-latency and high-throughput applications. 

### Current situation

TPL and async .NET APIs , as well as numerous 3rd-party libraries, use ```Task``` in their public APIs and implementations. This is an unfortunate impediment for writing performant applications.

For this reason, C# 7 offers ability to return awaitable structs from async methods. This significantly improves the situation, but neither .NET Framework, nor TPL, nor even CoreFxLab offer anything that makes use of it. Except for the `ValueTask`, which is simply a struct that wraps `Task` object. In the above example, on one hand, it reduces 3M `Task` objects to 1M. On the other hand, it's still bad.

NWheels APIs and implementations should not suffer from this problem.

### Solution

Create asynchronous programming model, based entirely on value types. In this way, asynchronous execution paths will not trigger garbage collection. Under heavy load, performance gain can be huge.

I suggest adopting the well-known concept of promises, and implement an awaitable struct `Promise<T>`. 

The struct will be configured with three callbacks:
- on success: `Action<T>`
- on failure: `Action<Exception>`
- on timeout (advanced feature): `Action<TimeSpan>`

Methods:
- resolve: `void Resolve(T value)`
- reject: `void Reject(Exception error)`
- timeout (advanced feature): `void Timeout(TimeSpan duration)`

Constructors:
- ctor(Task, onSuccess, onFailure, onTimeout, TimeSpan timeout)
- ctor(onSuccess, onFailure, onTimeout, TimeSpan timeout)

`Promise<T>` will also implement `GetAwaiter()` as required by C# compiler.

**Comment by ILyaIL83** [comment]
Sounds very serious optimization. 
Why do we need first constructor with Taks?
Is GetAwaiter() implementation enough for await async syntax usage?

**Comment by ILyaIL83** [comment]
So this interfaces should be implemented to be able work with awaitable-awaiter pattern:

```
public interface IAwaitable
{
    IAwaiter GetAwaiter();
}

public interface IAwaiter : INotifyCompletion 
{
    bool IsCompleted { get; }
    void GetResult();
}
```
or generic vesion:
```
public interface IAwaitable<out TResult>
{
    IAwaiter<TResult> GetAwaiter();
}

public interface IAwaiter<out TResult> : INotifyCompletion // or ICriticalNotifyCompletion
{
    bool IsCompleted { get; }
    TResult GetResult();
}
```

**Comment by felix-b** [comment]
### A surprise

My first step was to reproduce the problem through benchmarks. To my surprise, I wasn't able to reproduce it. 

Code that uses `Task` actually worked faster than code that uses `ValueTask`. Moreover, a function that allocated a small object and returned a reference to it, worked faster than function that initialized a small struct and returned it to the caller by value.

I'm not sure if it's related to recent improvements in GC. With .NET Core, we have no `perfmon`, so it will require more efforts to gather exact picture of what's happening -- doing something like this:
- http://blogs.microsoft.co.il/sasha/2017/02/27/profiling-a-net-core-application-on-linux/
- http://blogs.microsoft.co.il/sasha/2017/03/30/tracing-runtime-events-in-net-core-on-linux/

Still, even such coarse measurements as memory consumption by the process, and number of operations completed in 1 minute, shows that my initial assumptions were wrong.

I believe we must understand what happens and why, so I don't close this issue, but I move it to the Backlog for now.

Meanwhile, we will use conventional `Task`-based async methods in our APIs and impementations.

**Comment by ILyaIL83** [comment]
Great news :)
