### ISSUE TITLE
Web client architecture: modules strategy

### ISSUE THREAD

**Issue by ILyaIL83** [nwheels-io/NWheels#55]
There are few recommended strategies for modules separation https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#q-module-recommendations 
- Domain feature modules.
- Routed feature modules.
- Routing modules.
- Service feature modules.
- Widget feature modules.
- Our own strategy or mix?

We have to decide/agree/choose.

**Comment by felix-b** [comment]
Sounds interesting. I will review it later on today.

**Comment by felix-b** [comment]
This appears to be quite a wide topic, and it requires experience writing Angular applications. I would suggest not seeking the ultimately right answer at this moment. Let's start with what seems to fit, and make changes as we build better understanding and experience with Angular. Also, look for what fits the server-side model of pluggable features.
