### ISSUE TITLE
MVP demo application

### ISSUE THREAD

**Issue by felix-b** [nwheels-io/NWheels#83]
We need an MVP demo application that would demonstrate the strengths of the framework.

**Comment by felix-b** [comment]
## MVP application spec

Here I summarize a discussion that took place offline

### Requirements

Create a billing application for a power plant operator. The application is responsible to:

- collect electricity consumption data
- calculate charging and billing information
- produce bills to customers
- process customers' payments and manage debt collection

The application will serve the following actors:

- Sensors (running on an IoT cloud): push consumption data to the application
- Operator users: use administration UI for back-office management
- Customers: use personal dashboard UI for payment and reporting

**Comment by felix-b** [comment]
Comments and suggestions are welcome! A BDD-style specification (given-when-then) would be very useful...

**Comment by felix-b** [comment]
## Proposed architecture

(work in progress -- suggestions are welcome)

### Microservices (~ subdomains)

- Sensor lisneter service
    - daemon
    - hosts API endpoint for sensors to push consumption data
    - owns sensors and ongoing consumption data
- Billing service
    - batch job
    - runs periodically and calculates ongoing billing data
    - owns calculated billing data and invoices
- Customer service
    - daemon
    - hosts API for operations on customers and tariffs
    - ....
- Administration UI service
    - daemon; hosts admin web app for back-office users
- Dashboard UI service
    - daemon; hosts dashboard web app for customer users

**Comment by felix-b** [comment]
### Data flow diagram

![nwheels-mvp-dataflow-diagram](https://user-images.githubusercontent.com/5800163/36034607-406ad002-0dbd-11e8-97b0-78e057039865.png)

### Entity relationship diagram

![nwheels-mvp-demo-erd 5](https://user-images.githubusercontent.com/5800163/36058471-72d08e44-0e29-11e8-8520-5997cfb590ab.png)

(work in progress -- suggestions are welcome)

### Microservices (~ subdomains)

- **Sensor service** (red color)
    - Type: daemon
    - Responsibilities
        - manages list of **Sensors**
        - hosts REST API endpoint for IoT cloud to push sensor readings
        - hosts REST API endpoint for administrative transaction requests 
        - hosts REST API endpoint for querying/observing owned entities
    - Owned entities:
        - **Sensor**
        - **Sensor Reading**
- **Customer service** (cyan color)
    - Type: daemon
    - Responsibilities
        - performs data queries and transactions on the Customers subdomain
        - hosts REST API endpoint for administrative transaction requests 
        - hosts REST API endpoint for querying/observing owned entities
    - Owned entities:
        - Tariff: a tariff plan
        - Customer: a party whose electricity consumption is measured by one or more Sensors
        - Contract: an association which tells that _Sensor X belongs to Customer Y under the Tariff Z_
- **Billing Service** (purple color)
    - Type: batch job; runs on schedule
    - Responsibiliies
        - generates invoices based on sensor readings and customer contracts
    - Owned entities:
        - InvoiceRow
        - Invoice
- **Payment Service** (green color)
    - Type: daemon
    - Responsibiliies
        - integrates with online payment services to process customer's payments
        - stores customer payment receipts (in general, customer's debt is calculated as total invoices less total receipts).
    - Owned entities:
        - PaymentMethod: stores details of customer's payment method. This is an abstract entity, inherited by implementation of integration with each concrete payment service; this is because each payment service requires different information; for example, PaypalPaymentMethod will contain PayPal email address.
        - Receipt: represents a completed successful payment 
- **User Account Service** (yellow color)
    - Type: daemon
    - Responsibiliies
        - manages user account information and credentials
        - performs user authentication
    - Owned entities:
        - UserAccount: an abstract entity, inherited per different kind of user
            - DashboardUserAccount: for customers to login to Dashboard web app 
            - OfficeUserAccount: for operator's staff to login to Admin web app
- **Administration Web App**
    - Type: daemon
    - Responsibiliies
        - hosts administration web app for back-office users
- **Dashboard Web App**
    - Type: daemon
    - Responsibiliies
        - hosts dashboard web app for customer users

**Comment by godrose** [comment]
Looking good.
No need in supporting all kinds of price plans and currencies right from the start.
Also i recommend replacing the word "tariff" with "price plan"

**Comment by godrose** [comment]
Why there's need in two different apps? One app might be enough for demo purposes.
The user will be redirected according to their identity to the according root view

**Comment by felix-b** [comment]
@godrose yes, I agree about not implementing variations of pricing strategies etc right from the start. Just wanted to illustrate how they are planned to be implemented. 

"Pricing Plan" indeed sounds better. "Rate Plan" can also be good -- here is an [indication of usage from Google Books](  https://books.google.com/ngrams/graph?content=tariff+plan%2Crate+plan%2Cpricing+plan&year_start=1800&year_end=2008&corpus=17&smoothing=3&share=&direct_url=t1%3B%2Ctariff%20plan%3B%2Cc0%3B.t1%3B%2Crate%20plan%3B%2Cc0%3B.t1%3B%2Cpricing%20plan%3B%2Cc0)

As for having 1 or 2 apps, I'd like to demonstrate a production-ready system, so I'd rather apply considerations about production. Since the apps serve two different kinds of users, I'm considering these points:
- The style/theme can differ, which affects the login page itself (ascetic vs attractive)
- The set of credentials can differ (AD/SSO and/or 2-factor vs email/password + captcha)
- Options like "forgot password" or "don't have an account? sign up" might not be relevant for both kinds of users.
- Last but not least, having 2 separate apps allows granular deployment and availability. The apps can be independently upgraded. Or if one app is taken down, the other one can still be operational.

One interesting alternative is display 2 different login forms on a common login page. But then we have 3 apps: login, back office, and dashboard.

**Comment by felix-b** [comment]
## List of microservices (~ subdomains)

Service|Responsibilities|API Endpoints
---|---|---
**Sensor service** (red color, daemon)|Sensors subdomain; store sensor readings|(1) push sensor readings (2) TX = submit transaction requests (3) QX = run entity queries
**Customer service** (cyan color, daemon)|Customers subdomain; manage pricing plans and contracts|TX, QX
**Billing service** (purple color, daemon)|Billing subdomain; query and invalidate invoices|TX, QX
**Billing job** (purple color, batch job)|Generate invoices based on data from Sensors and Customers subdomains|N/A
**Payment service** (green color, daemon)|Payment subdomain + process payments through integration with online payment services|TX, QX + callback endpoints specific to payment services
**Login service** (yellow color, daemon)|User Accounts subdomain + authenticate users|TX, QX
**Admin App** service|Host back-office web app|Web
**Dashboard App** service|Host dashboard web app|Web

**Comment by felix-b** [comment]
## Thoughts on DDD-like design of domain objects

Forces:

- We want our domain objects to be as POCO as possible. We don't want to clutter our code with any framework-specific stuff.
- We want our domain objects to be self-explanatory. For that, we want to utilize the full power of OOP. That is, use visibility (public/protected/...), polymorphism (abstract/virtual/...), and read/write (get/set) modifiers to express our design intentions. We don't want a framework to steal the expressiveness of our models, for example by forcing members to be virtual.
- We don't want to implement the logic of common semantics and constraints (such as unique, required, immutable, value validations, etc etc) by ourselves. We want to transparently delegate these basic functions to the framework.
- We want the configuration of common semantics and constraints to be as readable and as easy discoverable as possible. The ideal solution would let us see these characteristics in IntelliSense, in the member info balloons.
- We want developers workflow to be simple. For example, we don't want the workflow implemented in the Afra version: first declare all entities as interfaces; then, write abstract classes for entities that have methods and logic; then register the abstract classes as entity implementations in DI composition root. It was complex, bloating, and error-prone.
- We want the testing to be straightforward. 
(work in progress - TBD)

**Comment by felix-b** [comment]
### Progress update

What's ready for review by now:

- The sample application is in the PR branch `pr-mvp`
    - https://github.com/felix-b/NWheels/tree/pr-mvp/Samples/02-ElectricityBilling/ElectricityBilling
- SLN file: 
    - https://github.com/felix-b/NWheels/blob/pr-mvp/Samples/02-ElectricityBilling/ElectricityBilling/ElectricityBilling.sln

The solution is structured as follows:

- ElectricityBilling.Domain - _"shared kernel"_, all domain data and logic in one class library
- ElectricityBilling.XxxxxService - a microservice console app project; there is one per microservice

Note that the solution doesn't yet consume NWheels NuGet packages. Temporarily, a class library named NWheelsTempApiLib contains mocks of all NWheels APIs (https://github.com/felix-b/NWheels/tree/pr-mvp/Samples/02-ElectricityBilling/ElectricityBilling/NWheelsTempApiLib). The mocks are just for the application code to compile, they can't execute. 

This is still mid-work. The most of the progress was with the Sensor Service (https://github.com/felix-b/NWheels/tree/pr-mvp/Samples/02-ElectricityBilling/ElectricityBilling/ElectricityBilling.SensorService)
